name: Docker

on:
  repository_dispatch:
    types: publish-latest
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason"
        required: false
        default: "Manual trigger"
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - "maint-**"
      - "feature/**"

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cds-rdm

jobs:
  push:
    name: Publish images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Extract GIT metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          tags: |
            # set tag version if a tag is present. We use type=raw to avoid generate the latest tag automatically
            type=raw,value={{tag}},enable=${{ startsWith(github.ref, 'refs/tags/')}}
            # set latest tag for master branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            # set "latest" tags for maint branches
            type=raw,value={{branch}}-latest,enable=${{ startsWith(github.ref, 'refs/heads/') && github.ref != 'refs/heads/master' }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # required for caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and publish image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
