name: Docker

on:
  repository_dispatch:
    types: publish-latest
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - "maint-**"
      - "feature/**"

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cds-rdm

jobs:
  push:

    name: Publish images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract GIT metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            # set latest tag for default branch (master)
            type=raw,value=latest,enable={{is_default_branch}}
            # set "latest" tags for maint branches
            type=raw,value={{branch}}-latest,enable=${{ github.event_name != 'push tag' && github.ref != format('refs/heads/{0}', 'master') }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
