# -*- coding: utf-8 -*-
#
# Copyright (C) 2023 CERN.
#
# CDS-RDM is free software; you can redistribute it and/or modify it under
# the terms of the GPL-2.0 License; see LICENSE file for more details.

name: CI

on:
  push:
    branches:
      - master
      - "feature/*"
      - "maint-**"
  pull_request:
    branches:
      - master
      - "maint-**"
      - "feature/**"
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 3 * * 6"
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason"
        required: false
        default: "Manual trigger"

jobs:
  Python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.12]
        db-service: [postgresql14]
        search-service: [opensearch2]
        include:
          - db-service: postgresql14
            DB_EXTRAS: "postgresql"
    env:
      DB: ${{ matrix.db-service }}
      SEARCH: ${{ matrix.search-service }}
      EXTRAS: tests

    steps:
      - name: Install python-ldap dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsasl2-dev libldap2-dev libssl-dev

      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install Python dependencies
        run: |
          uv sync --locked
          uv pip list

      - name: Run tests
        working-directory: ./site
        run: ./run-tests.sh --ignore=cds_rdm/migration

  JS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use Node.js v20.x
        uses: actions/setup-node@v6
        with:
          node-version: v20.x

      - name: Run eslint test
        run: ./run-js-linter.sh -i
